version: "3.8"
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypass
    volumes:
      - pgdata:/var/lib/posgresql/data
  weather_service:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/weather_service
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  pgdata:
